### ISSUE TITLE
library "libmagnifying_glass_plugin.so" not found

### ISSUE THREAD

**Issue by raysonlim77** [alnitak/magnifying_glass#2]
Hi,Having issue while trying the package on my android device,how do i solve it? i really need the feature badly for my app.

Invalid argument(s): Failed to load dynamic library 'libmagnifying_glass_plugin.so': dlopen failed: library "libmagnifying_glass_plugin.so" not found

**Comment by alnitak** [comment]
Hi, seems it doesn't find the native c++ compiled source! Have you tried to run the example?

**Comment by raysonlim77** [comment]
Yes, i've tried to copy the whole example code to my app and its not working as well, do you have any idea to solve it?

**Comment by alnitak** [comment]
if you clone this repository and open that?
Also you can try to open the example/android folder with Android Studio and try to compile from there.
Another try we can do is to give me a simple project to let me see what wrong.
Or maybe you can try to:
`flutter run -v`
to see verbose compile output.

**Comment by alnitak** [comment]
I close this issue. Please, if you have any news tell me
